{
 "title": "wind-project",
 "time": { "from": "2023-02-13T16:03:28.692Z", "to": "2023-04-29T23:47:18.237Z" },
 "panels": [
  {
   "title": "Wind direction in Ceara",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp, direction_10, direction_100 from wind_project.wind"
    }
   ]
  },
  {
   "title": "Temperature 2m above ground level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, temperature_2 from wind_project.temperature"
    }
   ]
  },
  {
   "title": "Wind speeds in Ceara",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select timestamp, speed_10, speed_100, gusts_10 from wind_project.wind"
    }
   ]
  }
 ]
}